### ISSUE TITLE
always crash?! ;/

### ISSUE THREAD

**Issue by transfluxus** [mrzl/TheOracle#47]
No Words for this.
```
hi
java.lang.IllegalArgumentException: bound must be positive
null
	at java.util.Random.nextInt(Random.java:388)
	at oracle.markov.MarkovChain.getRandomSeed(MarkovChain.java:165)
	at oracle.markov.MarkovChain.generateSentence(MarkovChain.java:101)
	at oracle.MarkovManager.getAnswer(MarkovManager.java:49)
	at oracle.LacunaLabOracle.keyPressed(LacunaLabOracle.java:106)
```

**Comment by mrzl** [comment]
Gib ma die kompletten Logs vom start der app. Da sollte was passieren wie:

```
INFO : SimpleHTTPServer running on port 8000
Training chain with order 1
Training chain with order 2
Training chain with order 3
Training chain with order 4
Training chain with order 5
Training chain with order 6
Saved markov chain to data\v2-order1.data
Saved markov chain to data\v2-order2.data
Saved markov chain to data\v2-order3.data
Saved markov chain to data\v2-order4.data
Saved markov chain to data\v2-order5.data
Saved markov chain to data\v2-order6.data
*** Networks interfaces:
Teredo Tunneling Pseudo-Interface 2001:0:9d38:6abd:30f6:5cc2:a0a4:29ca
Teredo Tunneling Pseudo-Interface fe80:0:0:0:30f6:5cc2:a0a4:29ca%net1
Intel(R) Centrino(R) Advanced-N 6205 192.168.0.13
Intel(R) Centrino(R) Advanced-N 6205 2a02:8109:8c80:22a4:d43f:301b:aac5:f8f6
Intel(R) Centrino(R) Advanced-N 6205 fd00:8494:8c70:c222:d43f:301b:aac5:f8f6
Intel(R) Centrino(R) Advanced-N 6205 2a02:8109:8c80:22a4:712b:b478:5ce0:b5ef
Intel(R) Centrino(R) Advanced-N 6205 fd00:8494:8c70:c222:9ac:2c2d:3c3d:509d
Intel(R) Centrino(R) Advanced-N 6205 fe80:0:0:0:d43f:301b:aac5:f8f6%wlan0
VirtualBox Host-Only Ethernet Adapter 192.168.56.1
VirtualBox Host-Only Ethernet Adapter fe80:0:0:0:8070:e597:3960:a02c%eth7
******
```

Kann sein, dass du die aktuellen Texte noch nich hast, ich werde das mal checken.

**Comment by transfluxus** [comment]
```
INFO : SimpleHTTPServer running on port 8000
java.io.FileNotFoundException: data/text/oraclev2/v2_combined.txt (No such file or directory)
Training chain with order 1
java.io.FileNotFoundException: data/text/oraclev2/v2_combined.txt (No such file or directory)
Training chain with order 2
java.io.FileNotFoundException: data/text/oraclev2/v2_combined.txt (No such file or directory)
Training chain with order 3
java.io.FileNotFoundException: data/text/oraclev2/v2_combined.txt (No such file or directory)
Training chain with order 4
java.io.FileNotFoundException: data/text/oraclev2/v2_combined.txt (No such file or directory)
Training chain with order 5
java.io.FileNotFoundException: data/text/oraclev2/v2_combined.txt (No such file or directory)
Training chain with order 6
Saved markov chain to data/v2-order1.data
Saved markov chain to data/v2-order2.data
Saved markov chain to data/v2-order3.data
Saved markov chain to data/v2-order4.data
Saved markov chain to data/v2-order5.data
Saved markov chain to data/v2-order6.data
*** Networks interfaces:
awdl0 fe80:0:0:0:e80a:1fff:fe5a:4cb7%awdl0
en1 fe80:0:0:0:6203:8ff:fef2:8afc%en1
en1 192.168.2.101
******
No Words for this.
hi
null
java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at oracle.markov.MarkovChain.getRandomSeed(MarkovChain.java:165)
	at oracle.markov.MarkovChain.generateSentence(MarkovChain.java:101)
	at oracle.MarkovManager.getAnswer(MarkovManager.java:49)
	at oracle.LacunaLabOracle.keyPressed(LacunaLabOracle.java:105)
	at processing.core.PApplet.keyPressed(PApplet.java:3055)
	at processing.core.PApplet.handleKeyEvent(PApplet.java:2931)
	at processing.core.PApplet.dequeueEvents(PApplet.java:2605)
	at processing.core.PApplet.handleDraw(PApplet.java:2413)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1527)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)
hino
```

**Comment by mrzl** [comment]
und loift jetzt?

**Comment by transfluxus** [comment]
> purpose in the hacker, class turns out ofcollege, burned his procedure as cosmic credibility of different fashions also used to the application of his
